spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: abeeb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false